# Generated by Django 4.2.7 on 2023-11-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_upvote_answer_remove_upvote_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(max_length=3, related_name='questions', to='app.tag'),
        ),
    ]
