# Generated by Django 4.2.7 on 2023-11-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
