# Generated by Django 4.2.7 on 2023-11-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tag_tag_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_number',
        ),
        migrations.AddField(
            model_name='upvote',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], default=1),
            preserve_default=False,
        ),
    ]
