# Generated by Django 4.2.7 on 2023-11-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, max_length=3, related_name='questions', to='app.tag'),
        ),
    ]
