# Generated by Django 4.2.7 on 2023-11-15 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(max_length=256, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='app.question'),
        ),
    ]
