# Generated by Django 4.2.7 on 2023-12-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_answer_user_alter_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='Question.jpeg', null=True, upload_to='avatar/%Y/%M/%D'),
        ),
    ]
